---
title: "Model&coefficient_information"
author: "Yoo Ri Hwang"
date: '2022-06-09'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Sibling comparison Model

## sib0
No interaction  
gender compositoin: mixed sex vs same sex

(y_diff  ~ y_mean + con_mean + con_diff + gender_composition_two_eff, data=dat3)

$$y_{diff} = \beta_{0} + \beta_{1}y_{mean} + \beta_{3}Con_{mean}+ \beta_{3}Con_{diff} + \beta_{4}genderComposition_{two eff}$$

$$health_{diff} = \beta_{0} + \beta_{1}health_{mean} + \beta_{3}edu_{mean}+ \beta_{3}edu_{diff} + \beta_{4}genderComposition_{two level}$$
The coefficient in plots : meaning

con: continuous : education  
con_mean: education mean in sibling pair  
con_diff: education difference score in sibling pair  
gender composition two eff : mixed vs same sex (eff=effect coding)

## sib1
no intearction
gender composition = three level (mm, ff, mixed)
because this have three levels, we have two variables. 

 lm(y_diff  ~ y_mean + con_mean + con_diff + ev1 + ev2, data=dat3) // ev = effect code variable 

$$y_{diff} = \beta_{0} + \beta_{1}y_{mean} + \beta_{3}Con_{mean}+ \beta_{3}Con_{diff} + \beta_{4}ev1_{three eff}+\beta_{5}ev1_{threeeff}$$

$$health_{diff} = \beta_{0} + \beta_{1}health_{mean} + \beta_{3}edu_{mean}+ \beta_{3}edu_{diff} + \beta_{4}genderComposition1_{three level} +\beta_{5}genderComposition2_{three level} $$
The coefficient in plots : meaning

con: continuous : education  
con_mean: education mean in sibling pair  
con_diff: education difference score in sibling pair

gender composition variable (=ev1, ev2)

ev1  : effect code variable (mixed vs 11) 1/-1 is for male/femlae  
ev2 : effect code variable (mixed vs -1-1)

## sib2
gender composition: two level (mixed vs same)
interaction included

lm(y_diff  ~ y_mean + con_mean + con_diff + gender_composition_two_eff + gender_composition_two_eff:con_diff
                     , data=data)

$$y_{diff} = \beta_{0} + \beta_{1}y_{mean} + \beta_{3}Con_{mean}+ \beta_{3}Con_{diff} + \beta_{4}genderComposition_{two eff} + \beta_{5}genderComposition_{two eff} * Con_{diff}$$

$$health_{diff} = \beta_{0} + \beta_{1}health_{mean} + \beta_{3}edu_{mean}+ \beta_{3}edu_{diff} + \beta_{4}genderComposition_{two level} +\beta_{5}genderComposition_{two eff} * edu_{diff}$$
The coefficient in plots : meaning  

con: continuous : education    
con_mean: education mean in sibling pair    
con_diff: education difference score in sibling pair    
gender composition two eff : mixed vs same sex (eff=effect coding)  
con_diffxgender_composition_two_eff : interaction between con_diff and   gender_composition_two_level   


## sib3 

gender compisition: three level (mm ff mixed)  
interaction included 
because this have three levels, we have two variables. 

sib_model<- lm(y_diff  ~ y_mean + con_mean + con_diff + ev1 + ev2 +
                       ev1*con_diff + ev2*con_diff, data=data)


$$y_{diff} = \beta_{0} + \beta_{1}y_{mean} + \beta_{3}Con_{mean}+ \beta_{3}Con_{diff} + \beta_{4}ev1_{three eff}+\beta_{5}ev1_{three eff} + \beta_{6}ev1_{three eff}*con_{diff} +\beta_{7}ev2_{three eff}*con_{diff} $$

$$health_{diff} = \beta_{0} + \beta_{1}health_{mean} + \beta_{3}edu_{mean}+ \beta_{3}edu_{diff} + \beta_{4}genderComposition1_{three level} +\beta_{5}genderComposition2_{three level}+ \beta_{6}ev1_{three eff}*con_{diff} +\beta_{7}ev2_{three eff}*con_{diff} $$
The coefficient in plots : meaning

con: continuous : education  
con_mean: education mean in sibling pair  
con_diff: education difference score in sibling pair

gender composition variable (=ev1, ev2)

ev1  : effect code variable (mixed vs 11) 1/-1 is for male/femlae
ev2 : effect code variable (mixed vs -1-1)


con_diffxev1 : interaction between ev1 and education difference
con_diffxev2 : intearction between ev2 and education difference




# MLM
##  MLM0

null model

$$y_{ij} = \beta_{0j} + e_{ij}$$
$$ \beta_{0j} = \gamma_{00} + u_{0j}$$

## MLM1

MLM1: NO level 2 model without interaction

lmer(y~1 + catwtn + con +  (1|pid), data=data)  

y = health     
catwtn = cat within = gender within = individual gender    
con = education    

## MLM2

MLM1: NO level 2 model with interaction  

lmer(y~1 + catwtn + con + catwtn*con + (1|pid), data=data)  

extracted coefficient name version  

y = health  
con = continuous = education  
catwtn = cat within = individual gender  
catwtnxcon = interaction between individual gender and education  

## MLM3

level 2 variable: gender composition (mixed vs same)  
No interaction   

lmer(y ~ 1 + con + catbtw +  (1|pid), data=data)   

$$y_{ij} = \beta_{0j} + \beta_{1j}*edu + e_{ij}$$
$$ \beta_{0j} = \gamma_{00} + \gamma_{01}*genderComposition + u_{0j}$$
$$ \beta_{1j} = \gamma_{10}$$



catbtw : gender composition : categorical between    

### MLM4

gender composition: two level : mixed vs same   
with interaction    


lmer(y ~ 1 + con + catbtw + con:catbtw + (1|pid), data=data)   

con: education   
catbtw: gender composition   
conxcatbtw : interaction between education and gender composition   

### MLM5

gender composition : three levels (mm ff mixed )   
without interaction   

lmer(y ~ 1 + con + ev1 + ev2
                       + (1|pid), data=data)   
                       
con: education   

since gender composition has three levels,    
effect coded variable should be two : ev1 and ev2   




## MLM6

gender composition: three levels (mm ff mixed )   
with interaction   

 lmer(y ~ 1 + con + ev1 + ev2 + ev1:con + ev2:con
                             + (1|pid), data=data)   
                             

in extracted form,   

conxev1 : interaction between continuous (edu) and ev1   
conxev2 : interaction between continuous (edu) and ev2   


so, coef_fixed_conxev2_p_MLM6   

this variable means coeffcient, fixed effect, interaction between continuous (edu) and ev2's p-value in MLM6 model.    

                             
## 

Model   description   interaction	    coding type	    levels
<!------------------------------------------------------>
sib0    dyad model    no	            ss v os	        2
sib1    dyad model    no              mm v ff v mix	  3
sib2	  dyad model    yes             ss v os	        2
sib3    dyad model    yes             mm v ff v mix	  3
mlm0    mlm	          no              NA	            0
mlm1    mlm	          no              ??? 	          ???
mlm2    mlm	          yes             ??? 	          ???
mlm3    mlm	          no              ss v os         2
mlm4    mlm	          yes             ss v os         2
mlm5    mlm	          no	            mm v ff v mix	  3
mlm6    mlm	          yes             mm v ff v mix	  3
